export const STRINGS = {
  GOOGLE_SIGN_IN: 'Sign in with Google',
  NOTE_TAKING_APP: {
    PART1: 'Note-Ta',
    PART2: 'king App',
  },
  LOG_IN: 'Log In',
  SIGN_OUT: 'Sign Out',
  SAVE_SHARE_NOTES: 'Save and share notes',
  CREATE_ACCOUNT: 'Create Account',
  HAVE_ACCOUNT: 'Already have an account?',
  ADD_LABEL: 'Add Label',
  LABEL_NAME: 'Label Name',
  RESET_PASSWORD: 'Reset Password',
  FIRST_NAME: 'First Name',
  FIRST_NAME_SMALL: 'firstName',
  LAST_NAME: 'Last Name',
  LAST_NAME_SMALL: 'lastName',
  EMAIL: 'Email',
  EMAIL_SMALL: 'email',
  PASSWORD: 'Password',
  PASSWORD_SMALL: 'password',
  PHONE_NUMBER: 'Phone Number',
  PHONE_NUMBER_SMALL: 'number',
  CONFIRM_PASSWORD: 'Confirm Password',
  CONFIRM_PASSWORD_SMALL: 'confirmPassword',
  SUBMIT: 'Submit',
  SIGN_UP_CONDITIONS:
    'By continuing, you agree to our Terms of Service and Privacy Policy.',
  FORGOT_PASSWORD: 'Forgot Password?',
  INVALID_CREDENTIALS: 'Invalid Credentials',
  EMPTY_CREDENTIALS: 'Missing Email or Password',
  TEMP_LABEL_1: 'Personal',
  TEMP_LABEL_2: 'Academic',
  TEMP_LABEL_3: 'Work',
  TEMP_LABEL_4: 'Others',
  TEMP_TITLE: 'Meeting Notes',
  TEMP_CONTENT:'Discussion points: project updates, deadlines, action items',
  FIREBASE:{
    USER:'user',
    NOTES:'notes',
    LABELS:'labels',
    REMINDER:'reminder'
  },
  THEME:'Theme',
  LIGHT:'Light',
  DARK:'Dark',
  UPDATE_IMAGE:'Update Image',
  VERSION:'Version',
  IS_LOGGED_IN:'isLogedIn',
  SETTINGS:'Settings',
  FIRST_NAME_WARNING:'Please enter your first name',
  LAST_NAME_WARNING:'Please enter your last name',
  EMAIL_WARNING:'Please enter email',
  PASSWORD_WARNING:'Please enter your password',
  AVAILABLE_SPACE:'Available Space',
  STORAGE:'20 .254 GB of 25 GB Used',
  NOTE:'Note-Taking App'
};
